<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="14.0.0" />
    <PackageReference Include="FluentValidation" Version="11.11.0" />
    <PackageReference Include="Hangfire" Version="1.8.18" />
    <PackageReference Include="Hangfire.SqlServer" Version="1.8.18" />
    <PackageReference Include="MailKit" Version="4.12.0" />
    <PackageReference Include="MediatR" Version="12.5.0" />
    <PackageReference Include="MimeKit" Version="4.12.0" />

	  <PackageReference Include="Serilog" Version="4.2.1-dev-02352" />
	  <PackageReference Include="Serilog.Enrichers.Environment" Version="3.0.1" />
	  <PackageReference Include="Serilog.Extensions.Hosting" Version="9.0.1-dev-02307" />
	  <PackageReference Include="Serilog.Sinks.MSSqlServer" Version="8.2.1-dev-00130" />
	  <PackageReference Include="Serilog.Sinks.Seq" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\InventoryManagementSystem.Domain\InventoryManagementSystem.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Features\Reports\Commands\" />
    <Folder Include="Features\Reports\Handler\CommandHandler\" />
  </ItemGroup>

</Project>
